# Generated by Django 6.0.4 on 2026-04-24 18:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('alumni', 'Alumni'), ('admin', 'Admin')], default='student', max_length=10)),
                ('university_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('department', models.CharField(default='CSE', max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='uploads/profiles/')),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('research_interests', models.TextField(blank=True)),
                ('expertise', models.TextField(blank=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('is_mentor_available', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_club_member', models.BooleanField(default=False)),
                ('club_name', models.CharField(blank=True, choices=[('', 'Select Club'), ('uap_programming_contest_club', 'UAP Programming Contest Club'), ('software_hardware_club', 'Software and Hardware Club'), ('cyber_security_club', 'Cyber Security Club, CSE, UAP'), ('career_development_club', 'Career Development Club'), ('math_club', 'Math Club'), ('research_publication_units', 'Research and Publication Units'), ('robotics_club', 'Robotics Club'), ('photography_club', 'Photography Club'), ('sports_club', 'Sports Club'), ('cultural_club', 'Cultural Club')], max_length=100)),
                ('club_position', models.CharField(blank=True, choices=[('', 'Select Position'), ('member', 'Member'), ('executive_member', 'Executive Member'), ('senior_executive', 'Senior Executive'), ('assistant_secretary', 'Assistant Secretary'), ('secretary', 'Secretary'), ('vice_president', 'Vice President'), ('president', 'President'), ('coordinator', 'Coordinator'), ('organizer', 'Organizer'), ('volunteer', 'Volunteer'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
