# Generated by Django 6.0.4 on 2026-04-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_club_verified',
            field=models.BooleanField(default=False),
        ),
    ]
