# Generated by Django 6.0.4 on 2026-04-24 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('hackathon', 'Hackathon'), ('competition', 'Competition'), ('training', 'Training'), ('career', 'Career Session')], max_length=20)),
                ('organizer_category', models.CharField(choices=[('club', 'Club Event'), ('non_club', 'Non-Club Event')], default='club', max_length=20)),
                ('club_name', models.CharField(blank=True, choices=[('uap_programming_contest_club', 'UAP Programming Contest Club'), ('software_hardware_club', 'Software and Hardware Club'), ('cyber_security_club', 'Cyber Security Club, CSE, UAP'), ('career_development_club', 'Career Development Club'), ('math_club', 'Math Club'), ('research_publication_units', 'Research and Publication Units'), ('robotics_club', 'Robotics Club'), ('photography_club', 'Photography Club'), ('sports_club', 'Sports Club'), ('cultural_club', 'Cultural Club')], max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=300)),
                ('registration_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
