# Generated by Django 6.0.4 on 2026-04-24 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('course_name', models.CharField(db_index=True, max_length=200)),
                ('semester', models.CharField(choices=[('1.1', 'Year 1 Semester 1'), ('1.2', 'Year 1 Semester 2'), ('2.1', 'Year 2 Semester 1'), ('2.2', 'Year 2 Semester 2'), ('3.1', 'Year 3 Semester 1'), ('3.2', 'Year 3 Semester 2'), ('4.1', 'Year 4 Semester 1'), ('4.2', 'Year 4 Semester 2')], db_index=True, max_length=10)),
                ('topic', models.CharField(max_length=200)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('file', models.FileField(upload_to='uploads/materials/')),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='materials.studymaterial')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('material', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='materials.studymaterial')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'material')},
            },
        ),
    ]
